version: '3.1'
services:
  database:
    container_name: webapp-hello-word-database
    image: postgres
    environment:
      POSTGRES_USER : root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: default-database
    ports:
      - "5432:5432"
