server:
  port: 8081

#MYSQL Server
#spring:
#  application:
#    name: ONLINE-CV
#  datasource:
#    url: jdbc:mysql://localhost:3306/onlinecv
#    username: root
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect

#POSTGRES
spring:
  datasource:
    url: jdbc:postgresql://172.23.0.3:5433/onlinecv
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never
  mail:
    host: localhost
    port: 1025
    username: glora
    password: leyla
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000